dbname: testdb

spring:
  r2dbc:
    url: r2dbc:h2:mem:///${dbname}
    username: sa
    password:
  flyway:
    url: jdbc:h2:mem:${dbname};DB_CLOSE_DELAY=-1
    baseline-on-migrate: true
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
  h2:
    console:
      enabled: true
      path: /h2

logging:
  level:
    org:
      springframework:
        transaction:
          interceptor: TRACE